[package]
name = "dt-backup"
version = "0.1.0"
authors = ["mwc"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
attohttpc = "0.17"
scraper = "0.12"
chrono = "0.4"
rss = "1.10"
